# Generated by Django 5.1.7 on 2025-03-19 22:29

import django.db.models.deletion
import modelCore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=modelCore.models.image_upload_handler,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attractions",
                        to="modelCore.park",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
