# Generated by Django 5.1.7 on 2025-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0002_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="attraction_type",
            field=models.CharField(
                blank=True, help_text="吸引設施類型", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="destination_id",
            field=models.UUIDField(blank=True, help_text="關聯的目的地ID", null=True),
        ),
        migrations.AddField(
            model_name="attraction",
            name="entity_type",
            field=models.CharField(
                blank=True, help_text="實體類型", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="外部系統的ID", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="parent_id",
            field=models.UUIDField(blank=True, help_text="父實體ID", null=True),
        ),
        migrations.AddField(
            model_name="attraction",
            name="timezone",
            field=models.CharField(
                blank=True, help_text="時區信息", max_length=100, null=True
            ),
        ),
    ]
