# Generated by Django 5.1.7 on 2025-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modelCore",
            "0003_attraction_attraction_type_attraction_destination_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="latitude",
            field=models.FloatField(blank=True, help_text="緯度", null=True),
        ),
        migrations.AddField(
            model_name="attraction",
            name="longitude",
            field=models.FloatField(blank=True, help_text="經度", null=True),
        ),
    ]
