# Generated by Django 5.1.7 on 2025-03-20 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0004_attraction_latitude_attraction_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="評分，1-5分",
                    ),
                ),
                ("content", models.TextField(help_text="評論內容")),
                (
                    "visit_date",
                    models.DateField(blank=True, help_text="遊玩日期", null=True),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="是否發布"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attraction",
                    models.ForeignKey(
                        help_text="關聯的遊樂設施",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="modelCore.attraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="發表評論的用戶",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "遊客評論",
                "verbose_name_plural": "遊客評論",
                "ordering": ["-created_at"],
                "unique_together": {("user", "attraction", "visit_date")},
            },
        ),
    ]
