# Generated by Django 5.1.7 on 2025-03-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0005_guestreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
